### ISSUE TITLE
Replicable database base data

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics-data#5]
*Depends on #3, read the overview there first*.

### Task
- [ ] List which tables contain 'system data'
- [ ] Create process and tools to make copy of the data
- [ ] Keep a copy of that data at this repo
- [ ] Update any task meant to replicate a database from scratch to include this data
